import { useState, useMemo } from 'react';
import Head from "next/head";
import Link from 'next/link';
import Image from "next/image";
import { FaShoppingCart } from 'react-icons/fa';
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
//import styles from "@/styles/Product.module.css";
import { useCart} from '@/hooks/use-cart';
import products from '../products.json'



import Table from '../components/Table';
//import styles from "@/styles/Table.module.css";

const inter = Inter({ subsets: ["latin"] });



export default function Cart() {
   const { subtotal, totalItems, addToCart, checkout } = useCart();
   const {cartItems, updateItem} = useCart();

    console.log('cartItems',cartItems);

    const columns = [
        {
            columnId:'title',
            Header:'Product Name'
        },
        {
            columnId:'quantity',
            Header:'Quantity'
        },
        {
            columnId:'pricePerItem',
            Header:'Price Per Item'
        },
        {
            columnId:'total',
            Header:'Item Total'
        },
    
    ];

    const data = cartItems.map(item => {
        const product = products.find(({id})=> id === item.id)

        // set quantity to a react component
        const Quantity = () =>{

            function handleOnSubmit(e) {
                e.preventDefault();
                const inputs = Array.from(e.currentTarget.elements);
                const quantity = inputs.find(input => input.name === 'quantity')?.value;
                
                updateItem ({
                    id:item.id,
                    quantity:quantity && parseInt (quantity)
                })

                console.log('Submit', quantity);
            }
            
            return (
                <form onSubmit={handleOnSubmit}>
                    <input type="number" name="quantity" min={0} defaultValue={item.quantity} />
                    <button>Update</button>
                </form>
            );
        }

        return {
            ...item,
            quantity:<Quantity/>,
            total:item.quantity * item.pricePerItem,
            title:product.title
        }
    });
    // const data = [
    //     {
    //         id: 'my-product',
    //         title: 'My Cool Product',
    //         quanity: 1,
    //         pricePerUnit: 10.00,
    //         total: 10.00
    //     },
    //     {
    //         id: 'my-product',
    //         title: 'My Cool Product',
    //         quanity: 1,
    //         pricePerUnit: 10.00,
    //         total: 10.00
    //     },
    //     {
    //         id: 'my-product',
    //         title: 'My Cool Product',
    //         quanity: 1,
    //         pricePerUnit: 10.00,
    //         total: 10.00
    //     },
    //     {
    //         id: 'my-product',
    //         title: 'My Cool Product',
    //         quanity: 1,
    //         pricePerUnit: 10.00,
    //         total: 10.00
    //     }
    // ];

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main className={`${styles.main}`}>

              <h1 className={styles.buybutton} >
                  <FaShoppingCart size={40} /> Cart
              </h1>
              <p  >
                  <button className={styles.button} onClick={checkout}>
                      Check Out
                  </button>
              </p>
               
            <Table className = {styles.custom} columns = {columns} data = {data} />
    
      </main>
    </>
  );
}


